language: python

cache: pip

python:
  - "3.6"
install:
  - pip install -U -r requirements.txt
  - pip install mkdocs mkdocs-material pymdown-extensions

script:
- python -m compileall ./nabbot.py
- python -m compileall ./restart.py
- python -m compileall ./cogs
- python -m compileall ./utils
- cp CHANGELOG.md docs/changelog.md
- python -m mkdocs build

deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  local-dir: site
  keep-history: true
  verbose: true
  on:
    branch: master