language: python

cache: pip

python:
  - "3.6"
  - "3.7-dev"

matrix:
  allow_failures:
    - python: "3.7-dev"

install:
  - pip install -U -r requirements.txt
  - pip install -U -r requirements-docs.txt

script:
- python -m compileall ./nabbot.py
- python -m compileall ./restart.py
- python -m compileall ./cogs
- cp CHANGELOG.md docs/changelog.md
- python -m mkdocs build
- echo 'docs.nabbot.xyz' > ./site/CNAME

deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  local-dir: site
  keep-history: true
  verbose: true
  on:
    branch: master