site_name: NabBot
site_description: A Discord bot for the MMO Tibia
site_author: Allan Galarza


theme:
  name: material
  palette:
    primary: 'deep-purple'
    accent: 'orange'
  logo: 'assets/images/icon.png'
  favicon: 'assets/images/favicon.ico'
  feature:
    tabs: true

markdown_extensions:
  - toc:
        permalink: true
  - admonition
  - codehilite
  - pymdownx.superfences
  - pymdownx.details
  - pymdownx.inlinehilite
  - pymdownx.tilde
  - meta


google_analytics:
  - UA-111299710-2
  - auto

extra:
  social:
    - type: 'github'
      link: 'https://github.com/galarzaa90'
    - type: 'gitlab'
      link: 'https://gitlab.com/Galarzaa90'
    - type: 'discord'
      link: 'https://discord.me/NabBot'

repo_url: https://github.com/Galarzaa90/NabBot
edit_uri: ""
pages:
    - Home: index.md
    - Changelog: changelog.md
    - Install Guide: install.md
    - Permissions: permissions.md
    - FAQ: faq.md
    - Commands:
      - Overview: commands/index.md
      - Admin commands: commands/admin.md
      - General commands: commands/general.md
      - Loot commands: commands/loot.md
      - Mod commands: commands/mod.md
      - Owner commands: commands/owner.md
      - Roles commands: commands/roles.md
      - Tibia commands: commands/tibia.md
      - TibiaWiki commands: commands/tibiawiki.md
      - Tracking commands: commands/tracking.md
    - Customizing:
      - Configuration: customizing/config.md
      - Messages: customizing/messages.md
      - Cogs: customizing/cogs.md
